apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: default-security-context

spec:
  rules:
    - name: add-security-context
      match:
        any:
          - resources:
              kinds:
                - Pod

      mutate:
        patchStrategicMerge:
          spec:
            securityContext:
              runAsNonRoot: true

            containers:
              - (name): "*"
                securityContext:
                  allowPrivilegeEscalation: false
