apiVersion: kyverno.io/v1
kind: ClusterPolicy

metadata:
  name: generate-resourcequota

spec:
  rules:
    - name: create-resourcequota

      match:
        any:
          - resources:
              kinds:
                - Namespace

      generate:
        synchronize: true

        apiVersion: v1
        kind: ResourceQuota
        name: namespace-quota
        namespace: "{{request.object.metadata.name}}"

        data:
          spec:
            hard:
              requests.cpu: "4"
              requests.memory: 8Gi
              limits.cpu: "8"
              limits.memory: 16Gi
